// DO NOT EDIT
// Automatically generated by com.google.gwt.resources.css.InterfaceGenerator
package com.edukera.website.client.resources;
import com.google.gwt.resources.client.CssResource;
public interface StyleCssResource extends CssResource {
  
  String about();
  
  @ClassName("about-content")
  String aboutContent();
  
  @ClassName("button-language")
  String buttonLanguage();
  
  @ClassName("button-language-content")
  String buttonLanguageContent();
  
  @ClassName("button-language-item")
  String buttonLanguageItem();
  
  @ClassName("button-language-item-description")
  String buttonLanguageItemDescription();
  
  @ClassName("button-language-item-lang")
  String buttonLanguageItemLang();
  
  @ClassName("button-language-menu")
  String buttonLanguageMenu();
  
  String column();
  
  @ClassName("column-item")
  String columnItem();
  
  @ClassName("column-title")
  String columnTitle();
  
  @ClassName("column-wrapper")
  String columnWrapper();
  
  String columns();
  
  @ClassName("coming-soon")
  String comingSoon();
  
  @ClassName("coming-soon-content")
  String comingSoonContent();
  
  String connection();
  
  @ClassName("connection-button")
  String connectionButton();
  
  @ClassName("connection-button-content")
  String connectionButtonContent();
  
  @ClassName("connection-button-logo")
  String connectionButtonLogo();
  
  String container();
  
  @ClassName("container-feature")
  String containerFeature();
  
  @ClassName("container-feature-wrapper")
  String containerFeatureWrapper();
  
  @ClassName("container-hibert-wrapper")
  String containerHibertWrapper();
  
  @ClassName("container-hilbert")
  String containerHilbert();
  
  @ClassName("container-img")
  String containerImg();
  
  @ClassName("container-wrapper")
  String containerWrapper();
  
  String copyright();
  
  String error();
  
  String feature();
  
  @ClassName("feature-desc")
  String featureDesc();
  
  @ClassName("feature-logo")
  String featureLogo();
  
  @ClassName("feature-title")
  String featureTitle();
  
  @ClassName("feature-wrapper")
  String featureWrapper();
  
  String focus();
  
  String footer();
  
  @ClassName("footer-container")
  String footerContainer();
  
  String header();
  
  @ClassName("header-container")
  String headerContainer();
  
  @ClassName("hibert-name")
  String hibertName();
  
  @ClassName("hibert-photo")
  String hibertPhoto();
  
  @ClassName("hibert-wrapper")
  String hibertWrapper();
  
  String info();
  
  String input();
  
  @ClassName("input-button")
  String inputButton();
  
  @ClassName("input-button-content")
  String inputButtonContent();
  
  @ClassName("input-input")
  String inputInput();
  
  @ClassName("input-message")
  String inputMessage();
  
  @ClassName("input-message-content")
  String inputMessageContent();
  
  String logo();
  
  @ClassName("logo-calculus")
  String logoCalculus();
  
  @ClassName("logo-calculus-logo")
  String logoCalculusLogo();
  
  @ClassName("logo-calculus-operator")
  String logoCalculusOperator();
  
  @ClassName("logo-demo")
  String logoDemo();
  
  @ClassName("logo-demo-m0")
  String logoDemoM0();
  
  @ClassName("logo-demo-m1")
  String logoDemoM1();
  
  @ClassName("logo-demo-m2")
  String logoDemoM2();
  
  @ClassName("logo-demo-m3")
  String logoDemoM3();
  
  @ClassName("logo-logo-content")
  String logoLogoContent();
  
  @ClassName("logo-logo-wrapper")
  String logoLogoWrapper();
  
  @ClassName("logo-math")
  String logoMath();
  
  @ClassName("logo-proposition")
  String logoProposition();
  
  @ClassName("logo-qedu")
  String logoQedu();
  
  @ClassName("logo-reasoning")
  String logoReasoning();
  
  @ClassName("logo-reasoning-m0")
  String logoReasoningM0();
  
  @ClassName("logo-reasoning-m1")
  String logoReasoningM1();
  
  @ClassName("logo-reasoning-m2")
  String logoReasoningM2();
  
  @ClassName("logo-wrapper")
  String logoWrapper();
  
  String main();
  
  String product();
  
  @ClassName("product-content")
  String productContent();
  
  String quote();
  
  @ClassName("quote-close")
  String quoteClose();
  
  @ClassName("quote-open")
  String quoteOpen();
  
  String quote1();
  
  String quote2();
  
  String quote3();
  
  String saved();
  
  String soon();
  
  @ClassName("soon-firstline")
  String soonFirstline();
  
  @ClassName("soon-secondline")
  String soonSecondline();
  
  @ClassName("trans-all")
  String transAll();
  
  @ClassName("trans-all100")
  String transAll100();
  
  @ClassName("trans-all1000")
  String transAll1000();
  
  @ClassName("trans-all30")
  String transAll30();
  
  @ClassName("trans-all500")
  String transAll500();
  
  @ClassName("trans-all60")
  String transAll60();
  
  @ClassName("value-proposition")
  String valueProposition();
  
  @ClassName("value-proposition-container")
  String valuePropositionContainer();
  
  @ClassName("value-proposition-firstline")
  String valuePropositionFirstline();
  
  @ClassName("value-proposition-secondline")
  String valuePropositionSecondline();
  
  @ClassName("value-proposition-title")
  String valuePropositionTitle();
}

