// DO NOT EDIT
// Automatically generated by com.google.gwt.resources.css.InterfaceGenerator
package com.edukera.website.client.resources;
import com.google.gwt.resources.client.CssResource;
public interface StyleCssResource extends CssResource {
  
  String connection();
  
  @ClassName("connection-button")
  String connectionButton();
  
  @ClassName("connection-button-content")
  String connectionButtonContent();
  
  String container();
  
  @ClassName("container-img")
  String containerImg();
  
  @ClassName("container-wrapper")
  String containerWrapper();
  
  String container2();
  
  @ClassName("container2-wrapper")
  String container2Wrapper();
  
  String focus();
  
  String footer();
  
  String header();
  
  @ClassName("header-container")
  String headerContainer();
  
  String input();
  
  @ClassName("input-button")
  String inputButton();
  
  @ClassName("input-button-content")
  String inputButtonContent();
  
  @ClassName("input-input")
  String inputInput();
  
  String logo();
  
  @ClassName("logo-logo-content")
  String logoLogoContent();
  
  @ClassName("logo-logo-wrapper")
  String logoLogoWrapper();
  
  @ClassName("logo-math")
  String logoMath();
  
  @ClassName("logo-proposition")
  String logoProposition();
  
  @ClassName("logo-qedu")
  String logoQedu();
  
  @ClassName("logo-wrapper")
  String logoWrapper();
  
  String main();
  
  String soon();
  
  @ClassName("soon-firstline")
  String soonFirstline();
  
  @ClassName("soon-secondline")
  String soonSecondline();
  
  String tagphrase();
  
  @ClassName("tagphrase-first")
  String tagphraseFirst();
  
  @ClassName("tagphrase-second")
  String tagphraseSecond();
  
  @ClassName("trans-all")
  String transAll();
  
  @ClassName("trans-all100")
  String transAll100();
  
  @ClassName("trans-all1000")
  String transAll1000();
  
  @ClassName("trans-all30")
  String transAll30();
  
  @ClassName("trans-all500")
  String transAll500();
  
  @ClassName("trans-all60")
  String transAll60();
  
  @ClassName("value-proposition")
  String valueProposition();
  
  @ClassName("value-proposition-container")
  String valuePropositionContainer();
  
  @ClassName("value-proposition-firstline")
  String valuePropositionFirstline();
  
  @ClassName("value-proposition-secondline")
  String valuePropositionSecondline();
  
  @ClassName("value-proposition-title")
  String valuePropositionTitle();
}

