// DO NOT EDIT
// Automatically generated by com.google.gwt.resources.css.InterfaceGenerator
package com.edukera.website.client.resources;
import com.google.gwt.resources.client.CssResource;
public interface StyleCssResource extends CssResource {
}

