runtime: php55
api_version: 2

handlers:
- url: /bower_components
  static_dir: bower_components

- url: /css
  static_dir: css

- url: /fonts
  static_dir: fonts

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /min
  static_dir: min

- url: /legal
  script: legal.html

- url: /.*
  script: index.html
  secure: always
